site_name: CSC3206 AI Labs
site_url: https://ricwtk.github.io/ai-labs
docs_dir: src
site_dir: docs
theme:
  name: material
  custom_dir: "custom"
  favicon: img/favicon.ico
  logo: img/favicon.ico
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  features:
    - toc.integrate
    - navigation.tabs
markdown_extensions:
  - meta
  - pymdownx.tabbed
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra_css:
  - stylesheets/extra.css
nav:
  - Current:
    - Overview: index.md
    - get-start.md
    - lab1.md
    - lab2.md
    - lab3.md
    - lab4.md
    - lab5.md
    - lab6.md
    - lab7.md
    - lab8.md
    - lab9.md
  - Archive:
    - 202203:
      - archive/202203/get-start.md
      - archive/202203/lab1.md
      - archive/202203/lab2.md
      - archive/202203/lab3.md
      - archive/202203/lab4.md
      - archive/202203/lab5.md
      - archive/202203/lab6.md
      - archive/202203/lab7.md
      - archive/202203/lab8.md
      - archive/202203/lab9.md
    - 202103:
      - archive/202103/get-start.md
      - archive/202103/lab1.md
      - archive/202103/lab2.md
      - archive/202103/lab3.md
      - archive/202103/lab4.md
      - archive/202103/lab5.md
      - archive/202103/lab6.md
      - archive/202103/lab7.md
      - archive/202103/lab8.md
      - archive/202103/lab9.md
    - 202008:
      - archive/202008/get-start.md
      - archive/202008/lab1.md
      - archive/202008/lab2.md
      - archive/202008/lab3.md
      - archive/202008/lab4.md
      - archive/202008/lab5.md
      - archive/202008/lab6.md
      - archive/202008/lab7.md
      - archive/202008/lab8.md
      - archive/202008/lab9.md
    - 202003:
      - archive/202003/get-start.md
      - archive/202003/lab1.md
      - archive/202003/lab2.md
      - archive/202003/lab3.md
      - archive/202003/lab4.md
      - archive/202003/lab5.md
      - archive/202003/lab6.md
      - archive/202003/lab7.md
      - archive/202003/lab8.md
      - archive/202003/lab9.md
    - 201908:
      - archive/201908/lab1.md
      - archive/201908/lab2.md
      - archive/201908/lab3.md
      - archive/201908/lab4.md
      - archive/201908/lab5.md
      - archive/201908/lab6.md
      - archive/201908/lab7.md
      - archive/201908/lab8.md
      - archive/201908/lab9.md